config/routes.rb
Rails.application.routes.draw do
  resources :comments

  resources :articles

  devise_for :users
  resources :megazines

 root to: "megazines#index"

end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  belongs_to :megazine
  has_many :comments  
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :article
  has_many   :replies, class_name: "Comment", foreign_key: "parent"
  belongs_to :reply_comment, class_name: "Customer"
end

app/models/megazine.rb
class Megazine < ActiveRecord::Base
	has_many :articles
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  attr_reader :first_name ,:fullname ,:last_name

  has_many :articles  
  has_many :magazines 
  has_many :comments 

  def fullname
  	"#{self.first_name} #{self.last_name}"
  end    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?
  
  protected
  
    def configure_permitted_parameters
        devise_parameter_sanitizer.for(:sign_up) << :first_name  << :last_name
        devise_parameter_sanitizer.for(:account_update) << :first_name << :last_name
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:edit, :update, :destroy,:new]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new

    @article = Article.new(user_id: current_user.id , megazine_id: params[:megazine_id])
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :body, :user_id,:megazine_id,:author)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:destroy]
  before_action :authenticate_user!
 
  # POST /comments
  # POST /comments.json
  def create
    @comment = current_user.comments.build(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.js
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:body, :user_id, :article_id, :parent)
    end
end

app/controllers/megazines_controller.rb
class MegazinesController < ApplicationController
  before_action :set_megazine, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, only: [:edit, :update, :destroy,:new]

  # GET /megazines
  # GET /megazines.json
  def index
    @megazines = Megazine.all
  end

  # GET /megazines/1
  # GET /megazines/1.json
  def show
     @megazine = Megazine.includes(:articles).find(params[:id])
  end

  # GET /megazines/new
  def new
    @megazine = Megazine.new(user_id: current_user.id)
  end

  # GET /megazines/1/edit
  def edit
  end

  # POST /megazines
  # POST /megazines.json
  def create
    @megazine = Megazine.new(megazine_params)

    respond_to do |format|
      if @megazine.save
        format.html { redirect_to @megazine, notice: 'Megazine was successfully created.' }
        format.json { render :show, status: :created, location: @megazine }
      else
        format.html { render :new }
        format.json { render json: @megazine.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /megazines/1
  # PATCH/PUT /megazines/1.json
  def update
    respond_to do |format|
      if @megazine.update(megazine_params)
        format.html { redirect_to @megazine, notice: 'Megazine was successfully updated.' }
        format.json { render :show, status: :ok, location: @megazine }
      else
        format.html { render :edit }
        format.json { render json: @megazine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /megazines/1
  # DELETE /megazines/1.json
  def destroy
    @megazine.destroy
    respond_to do |format|
      format.html { redirect_to megazines_url, notice: 'Megazine was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_megazine
      @megazine = Megazine.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def megazine_params
      params.require(:megazine).permit(:title, :published, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/megazines_helper.rb
module MegazinesHelper
end

app/views/articles/_form.html.erb
  
  <%= form_for(@article ) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-inputs">
    <%= f.hidden_field :user_id %>
    <%= f.hidden_field :megazine_id %>
    <div class="field">
      <%= f.label :title %><br>
      <%= f.text_field :title,style:"width:90%" %>
    </div>
    <div class="form-group body">
      <label class="desc optional control-label" for="article_body">Body</label>
      <textarea class="string body optional form-control"  name="article[body]" column="30" style="width:90%"rows="5" id="body" require>
        <%= f.object.body %>
      </textarea>
    </div>
    <div class="field">
      <%= f.label :author %><br>
      <%= f.text_field :author,style:"width:90%"  %>
    </div>
  </div>
  <div class="form-actions">
    <%= f.button :submit,:class=>"btn btn-primary" %>
    <input class="btn btn-danger" type="reset" value="Reset">
  </div>
  <% end %>

<script>
  function textarea_height(e) {
    $(e).css({'height':'auto','overflow-y':'hidden'}).height(e.scrollHeight);
  }
  $('textarea').each(function () {
    textarea_height(this);
  }).on('input', function () {
    textarea_height(this);
  });
</script>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1>Listing Articles</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= link_to 'Show', article %></td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Article', new_article_path %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<h3>
  Article
</h3>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 id="article" data-article-id="<%= @article.id %>" ><%= @article.title %></h3>
      <p >
       <span style="float: right; margin-right: 20px;position: relative; bottom: 10px;"> Posted On: <%= @article.created_at.strftime('%a %d %b %Y')%></span>
        <span style="float: left; margin-left: 2px;position: relative; bottom: 10px;"> Author: <%= @article.author %></span>
      </p>
    </div>
    <div class="panel-body">
      <%= @article.body %>
    </div>
    <div class="panel-body">
        <%= link_to "Comments", "#" %>
        <ul id="comment_list" class="list-group">
          <% @article.comments.each do |comment | %>
            <li class="list-group-item" id='<%="comment_#{comment.id}"%>'>
                <span class="badge">
                <%= link_to "Remove", comment,method: "delete",remote: true %>
                </span> 
                <%= comment.body %> 
              </li>

          <% end %>
        </ul>
        <%= form_for(@article.comments.build ,remote: true,role: "form",:class=>"form-inline" ) do |f| %>
            <div class="form-group">
              <%= f.text_field :body ,placeholder: "Your comment...",:require=>true,:class=>"comment_body form-control"%>
            </div>
             <%= f.hidden_field :article_id %>
             <%= f.hidden_field :user_id %>
             <%= f.hidden_field :parent %>
             <%= f.submit "comment",:class=>'btn btn-default'%>
           
          <% end %>

    </div>
     <div class="panel-footer">
      <% if user_signed_in? && current_user == @article.user %>
        <%= link_to 'Edit', edit_article_path(@article) %> |
      <% end %> 
      <%= link_to "Back",@article.megazine %>    
    </div>
  </div>

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_field :body %>
  </div>
  <div class="field">
    <%= f.label :refrence %><br>
    <%= f.text_field :refrence %>
  </div>
  <div class="field">
    <%= f.label :refrence %><br>
    <%= f.text_field :refrence %>
  </div>
  <div class="field">
    <%= f.label :parent %><br>
    <%= f.number_field :parent %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/create.js.erb
$("#comment_list").append('<li class="list-group-item" id="<%="comment_#{@comment.id}"%>"> <span class="badge"><%= link_to "Remove", @comment,method: "delete",remote: true %></span><%= @comment.body %></li>');
$(".comment_body").val("");

app/views/comments/destroy.js.erb
var comment_id = "<%=@comment.id %>";
$("li#comment_"+comment_id).remove();

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Comments</h1>

<table>
  <thead>
    <tr>
      <th>Body</th>
      <th>Refrence</th>
      <th>Refrence</th>
      <th>Parent</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.body %></td>
        <td><%= comment.refrence %></td>
        <td><%= comment.refrence %></td>
        <td><%= comment.parent %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<p>
  <strong>Refrence:</strong>
  <%= @comment.refrence %>
</p>

<p>
  <strong>Refrence:</strong>
  <%= @comment.refrence %>
</p>

<p>
  <strong>Parent:</strong>
  <%= @comment.parent %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Magazine</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
 
</head>
<body>
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="<%= root_path %>">WebSiteName</a>
    </div>
    <div>
      <ul class="nav navbar-nav navbar-left">
        <li class="active"><a href="<%= megazines_path %>">Megazines</a></li>
         <li class="active"><a href="<%= new_megazine_path %>">Add Megazine</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
      	<% if user_signed_in? %>
          <li><%= link_to current_user.first_name ,"#",style:"color:white;"  %></li>
          <li><%= link_to "Logout" ,destroy_user_session_path,method: :delete  %></li>
          <li><%= link_to "Edit Profile" , edit_user_registration_path %></li>
        <% else %>
          <li><%= link_to new_user_registration_path do%>
          		<span class="glyphicon glyphicon-user"></span> Sign Up
          <% end %>
          </li>
          <li><%= link_to new_user_session_path  do%>
          		<span class="glyphicon glyphicon-log-in"></span> Login
          <% end %>		
          </li>
        <% end %>

      </ul>
    </div>
  </div>
</nav>
<% flash.each do | name , msg| %>
      <%= content_tag(:div, msg, class:"alert alert-info") %>
  <% end %>
<div class="container" >
  
  <div class="col-sm-9  main">
    <%= yield %>
  </div>
</div>


</body>
</html>

app/views/megazines/_form.html.erb
<%= form_for(@megazine) do |f| %>
  <% if @megazine.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@megazine.errors.count, "error") %> prohibited this megazine from being saved:</h2>

      <ul>
      <% @megazine.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
    <%= f.hidden_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :published %><br>
    <%= f.date_select :published %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/megazines/edit.html.erb
<h1>Editing Megazine</h1>

<%= render 'form' %>

<%= link_to 'Show', @megazine %> |
<%= link_to 'Back', megazines_path %>

app/views/megazines/index.html.erb
<div class="container">
  <h2>Listing Magazines</h2>
  <ul class="list-group">
    <% @megazines.each do |megazine| %>
        <li class="list-group-item">
          <span class="badge">
          <%= link_to 'Edit', edit_megazine_path(megazine) %>
          </span> 
          <%= link_to megazine.title , megazine %>
        </li>
    <% end %>
  </ul>
</div>

app/views/megazines/new.html.erb
<h1>New Megazine</h1>

<%= render 'form' %>

<%= link_to 'Back', megazines_path %>

app/views/megazines/show.html.erb
<h3>
	Magzine
</h3>
<div class="panel panel-default">
	<div class="panel-heading">
	  <h3><%=  @megazine.title %></h3>
	  <p style="float: right; margin-right: 20px;position: relative; bottom: 10px;"> Posted On: <%= @megazine.published.strftime('%a %d %b %Y')%>
	    
	  </p>
	</div>
	<div class="panel-body">
	 <p> Articles List</p>
		<ul>
			<% @megazine.articles.each do |article| %>
				<li><%= link_to article.title ,article %> </li>
			<% end %>
		</ul>
	</div>
	 <div class="panel-footer">
	  <% if user_signed_in? %>
	    <%= link_to 'Edit', edit_megazine_path(@megazine) %> |
	    <%= link_to "Add Article", new_article_path(megazine_id: @megazine.id)%> |
	  <% end %>  
	  <%= link_to "Back",@megazines_path%>
	</div>
</div>